version: '3.8'

services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1
    hostname: ${SQL_HOSTNAME} 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - ./sql_data:/var/opt/mssql  
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge
